server:
  port: 4000
camel:
  service:
    lra:
      enabled: true
      coordinator-url: http://lra-coordinator:8080
      local-participant-url: http://travel-pack-service:4000/api
  component:
    servlet:
      mapping:
        context-path: /api/*

